import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { connection } from "next/server"
import { Suspense } from "react"
import { Toaster } from "sonner"
import { extractRouterConfig } from "uploadthing/server"
import { Footer } from "@/components/layout/footer"
import { Header } from "@/components/layout/header"
import { ourFileRouter } from "./api/uploadthing/core"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

async function UTSSR() {
  await connection()

  return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="min-h-[calc(100vh-601px)] bg-brand-bg my-auto pt-16">
          <Header />
          <Suspense>
            <UTSSR />
          </Suspense>
          {children}
          <Footer />
          <Toaster richColors />
        </main>
      </body>
    </html>
  )
}
